### ISSUE TITLE
how many samples per second when you training?

### ISSUE THREAD

**Issue by mengzhibin** [zzh8829/yolov3-tf2#11]
Could you help tell your training speed? when i use other framework, the training speed is too slow.
thank you very much

**Comment by zzh8829** [comment]
For 416x416x3 images, you can train the full yolov3-tiny at about 140 images per second on Tesla M60 (comparable to GTX 1060). I didn't get a chance to test yolov3 yet, since I only been training the tiny version.

I also added some comments related to benchmark here https://github.com/zzh8829/yolov3-tf2/issues/2

**Comment by mengzhibin** [comment]
thanks very much for your nice work.
For I get slow speed in pytorch version, faster version is searching by me.
now I know your condition, I will close this question.
