### ISSUE TITLE
how to prepare my own dataset? I have images and their annotations.

### ISSUE THREAD

**Issue by sanku015** [zzh8829/yolov3-tf2#117]

**Comment by samcrane8** [comment]
Is it in pascal voc (xml) or darknet (txt) styled annotation? I have been consolidating my scripts into a python library so that it's more reusable. Here's a link to a script that converts xml to tfrecord. Hope it helps! 

https://github.com/samcrane8/Dataset_Toolkit/blob/master/scripts/export_to_tfrecord.py

**Comment by zzh8829** [comment]
https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md
