### ISSUE TITLE
How to implement transfer learning correctly. 

### ISSUE THREAD

**Issue by Robin2091** [zzh8829/yolov3-tf2#130]
Hi, I believe that training with randomly initialized weights is not very effective. Instead transfer darknet should be used to help the model converge and obtain good accuracy. On previous issues with transfer learning #48, it is stated that this code should be implemented. This is what I had in my train.py file. 

![image](https://user-images.githubusercontent.com/57192713/71312521-ce5bf180-23e0-11ea-8f9a-11f09cefdecb.png)

Is this how I am supposed to implement transfer learning(I did not set any flag arguments for transfer learning). On the new tutorial, it says to have a flag --mode fit transfer darknet. This is what the code does for that flag. 

![image](https://user-images.githubusercontent.com/57192713/71312538-0e22d900-23e1-11ea-8f48-26f85da21754.png)

Is this the same thing as I was doing? Or am I implementing transfer learning wrong?

**Comment by zzh8829** [comment]
Transfer learning in the old code only works with same number of classes. The new implementation works with mismatching number of classes.

Yolo network has 3 abstract layers
darknet -> yolo_conv -> yolo_output

the `darknet` mode means transfer darknet only and then freeze it,
`no_output` mode means transfer darknet + yolo_conv and freeze them together.

Your code is basically equivalent to darknet, but I recommend using the latest train.py since I have tested the correctness of that implementation.

**Comment by Robin2091** [comment]
@zzh8829  I understand, thank you.
