### ISSUE TITLE
Why are there 4 loss outputs? 

### ISSUE THREAD

**Issue by usama-ghufran** [zzh8829/yolov3-tf2#245]
On training, I see 4 loss outputs.
for example:

`loss: 7.3806 - yolo_output_0_loss: 0.0818 - yolo_output_1_loss: 0.2098 - yolo_output_2_loss: 0.2228`

Traditionally I used to get training and validation loss and accuracy which I understood quite well. So I knew how the training is happening. So what do these values above mean and how do I get the traditional output.

**Comment by zzh8829** [comment]
`loss` is the sum of all output loss plus some normalization loss. Accuracy only makes sense in the object classification context because theres clear right or wrong output. In bounding box detection there are output_0,1,2 because we have 3 box detector specializing different sizes. The more human friendly metrics would be mAP but I didn't implement that. The best way to understand the training progress is to just keep track of the first `loss` value
