### ISSUE TITLE
Modify the box coordinate while resize the image

### ISSUE THREAD

**Issue by LongxingTan** [zzh8829/yolov3-tf2#292]
Hey zzh8829,
Maybe I miss this part, and i realize that you have resize image function while parse_tfrecord and transform_image, did you modify the box accordingly while resize the image?

Maybe I miss it, and maybe that's the possible reason that someone can't get good result while train their own data.

Thanks, and as always, appreciate for your nice code

**Comment by Morgensol** [comment]
He is resizing without padding, and as such there is no need to modify the bounding boxes, because the bounding boxes are relative.

Say you have a corner which is 1/5 into the picture from top and 1/10th from the side. Say the picture is 10x5.
If you resize this to 5x5, the box will still be 1/5th of the picture from the top as we havent changed this, the pixel value will be the same (1). The image is squished in the y-coordinat to 5 from 10, effectivly meaning that 1/10th is no longer pixel 1, but pixel 0,5 (we are halving the pixel value because of the squish. Its easier to imagine if you sit down and draw it on a paper with small squares.

**Comment by LongxingTan** [comment]
@Morgensol 
Yes, you are right.
If without padding resize, that's enough and not necessary to modify it any more. Thanks
