### ISSUE TITLE
GPU ussage

### ISSUE THREAD

**Issue by ancoca13** [zzh8829/yolov3-tf2#80]
Hello,

Thanks for the great approach, I was looking for something like this to do some home proyects.

Sorry, but I'm quite new in this world.
I have installed the nvidia driver on ubuntu 18.04 as it is said in the readme and I have tried the GPU version but I didn't get any difference with CPU version regarding to performance.
Maybe it is because my graphic card is quite old (GTX765M) but it is extrange for me that the performance is not better or worst, just the same.

Could you tell me if I need any extra thing to use GPU or is there any way to check it the GPU is really doing the job?

Thanks in advance.

**Comment by AnaRhisT94** [comment]
Try this code:
```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 0.5GB of memory on the first GPU
  try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=500)])
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)
```
Also, have you installed the necessary CUDA, CUDNN to run this on GPU? and NVIDIA Drivers

**Comment by JulianOrteil** [comment]
@ancoca13 

The current Tensorflow-GPU release (which you are using) will not train on a GPU with a CUDA compute score below 3.5.
Your GTX765M is rated at 3.0, so Tensorflow won't even try to run on your GPU. It is defaulting to the CPU, so that is why you see no improvement in training times.

You can see here for the proper TF-GPU set up: https://www.tensorflow.org/install/gpu
You can also see here for the compute scores for every supported CUDA GPU: https://developer.nvidia.com/cuda-gpus
(Click on CUDA-Enabled GeForce and TITAN Products to see your GTX765M score; it is in the GeForce Notebook Products list)

**Comment by ancoca13** [comment]
Well, it`s a pity that I can't take advantage of my card for this.

Thanks to the three of you for your help!

**Comment by JulianOrteil** [comment]
Of course!

I am unsure as to the minimum scores for other TF 1.x releases. It may take a bit of work to get this project working on 1.x, but if you would like to experiment with the other releases, there is no stopping you.

**Comment by zzh8829** [comment]
You can use `nvidia-smi` to check the gpu usage but I don't think driver can do much in terms of performance
