### ISSUE TITLE
Questions about anchors

### ISSUE THREAD

**Issue by nivsmall** [zzh8829/yolov3-tf2#81]
Hey there!
I'm working on my own dataset and have a couple of questions:

From what i know YOLO is originally supposed to choose/modify it's anchors according to the dataset (by K-means or what not) but i found no trace of this in this repo, did I miss it out? are the anchors proposed for detection always the same as default?

Secondly, my dataset is pretty homogeneous in regards to box sizes and ratios. If i want to change the number of anchors in each grid can i just change yolo_anchrs & yolo_anchors_mask? from my understanding i will not need to go in to redefine the shapes of the tensors passed through propagations?

**Comment by DeltaTesting** [comment]
Hi,
Answering your first question, in this repo the anchors are hardcoded in the begining of model.py. But you can modify it to improve the accuracy in your environment. In my case to find better anchors i use a modification of the code you can find in this repo: [https://github.com/decanbay/YOLOv3-Calculate-Anchor-Boxes](url)

For the second question, I think you can not use less nor more than 9 anchors in yoloV3 without changing the network itself (see the YoloV3 implementation in models.py, how the output is generated). Maybe someone else can confirm that, since i'm not 100% sure.

**Comment by nivsmall** [comment]
thanx @DeltaTesting 
I found it best to find anchors by simple k-means clusters... your link doesn't seem to work for me, is it conceptually different from my proposal?

**Comment by DeltaTesting** [comment]
No, it is conceptually the same, k-means clustering. I just copy it because sometimes its easy to change a script in order to make it compatible with your data that doing it from scratch.

**Comment by zzh8829** [comment]
Yes you can modify the anchors in models.py. I don't believe you can modify the number of anchors since that will change the overall network structure.
